name: build
on: [push, pull_request]
jobs:
  vc17:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
    - name: Build executable
      run: nmake
    - uses: actions/upload-artifact@v4
      with:
        name: bsod.exe
        path: bsod.exe
        if-no-files-found: error
